version: '3.9'
services:
    user-service-postgres:
        container_name: user_service_postgres
        image: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
            PGDATA: /data/postgres
        volumes:
            - user-service-postgres:/data/postgres
        ports:
            - "5432:5432"
        restart: unless-stopped

volumes:
    user-service-postgres: